# Generated by Django 4.2.9 on 2025-11-21 20:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del anuncio', max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(help_text='Texto del anuncio que se publicará', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del anuncio (opcional)', null=True, upload_to='anuncios/', verbose_name='Imagen')),
                ('duracion_dias', models.PositiveIntegerField(default=30, help_text='Días durante los cuales se publicará', verbose_name='Duración (días)')),
                ('total_publicaciones', models.PositiveIntegerField(default=180, help_text='Número total de publicaciones a realizar', verbose_name='Total de Publicaciones')),
                ('active_time_start', models.PositiveIntegerField(default=5, help_text='Hora de inicio (0-23)', verbose_name='Hora de Inicio')),
                ('active_time_end', models.PositiveIntegerField(default=21, help_text='Hora de fin (0-23)', verbose_name='Hora de Fin')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de inicio de las publicaciones', verbose_name='Fecha de Inicio')),
                ('activo', models.BooleanField(default=False, help_text='Si el anuncio está activo', verbose_name='Activo')),
                ('publicaciones_programadas', models.BooleanField(default=False, help_text='Si las publicaciones fueron programadas en Celery', verbose_name='Publicaciones Programadas')),
                ('publicaciones_realizadas', models.PositiveIntegerField(default=0, help_text='Contador de publicaciones completadas', verbose_name='Publicaciones Realizadas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GrupoFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del grupo', max_length=255, verbose_name='Nombre del Grupo')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para publicaciones', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Grupo Facebook',
                'verbose_name_plural': 'Grupos Facebook',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del usuario de Facebook', max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(help_text='Contraseña del usuario de Facebook', max_length=255, verbose_name='Contraseña')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para publicar', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Usuario Facebook',
                'verbose_name_plural': 'Usuarios Facebook',
                'ordering': ['email'],
                'indexes': [models.Index(fields=['email'], name='publicadorF_email_66f863_idx'), models.Index(fields=['activo'], name='publicadorF_activo_09065f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicacionGrupoFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(blank=True, help_text='Fecha programada para la publicación', null=True, verbose_name='Fecha de Publicación')),
                ('exitosa', models.BooleanField(default=False, help_text='Si la publicación fue exitosa', verbose_name='Exitosa')),
                ('intentos', models.PositiveIntegerField(default=0, help_text='Número de intentos realizados', verbose_name='Intentos')),
                ('error', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True, verbose_name='Error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicadorFacebook.anuncio', verbose_name='Anuncio')),
                ('grupo_facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicadorFacebook.grupofacebook', verbose_name='Grupo Facebook')),
                ('usuario_publicador', models.ForeignKey(blank=True, help_text='Usuario que realizará la publicación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicadorFacebook.usuariofacebook', verbose_name='Usuario Publicador')),
            ],
            options={
                'verbose_name': 'Publicación en Grupo Facebook',
                'verbose_name_plural': 'Publicaciones en Grupos Facebook',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddField(
            model_name='grupofacebook',
            name='usuarios',
            field=models.ManyToManyField(help_text='Usuarios que pueden publicar en este grupo', related_name='grupos_facebook', to='publicadorFacebook.usuariofacebook', verbose_name='Usuarios'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='grupos_facebook',
            field=models.ManyToManyField(help_text='Grupos donde se publicará este anuncio', related_name='anuncios', through='publicadorFacebook.PublicacionGrupoFacebook', to='publicadorFacebook.grupofacebook', verbose_name='Grupos de Facebook'),
        ),
        migrations.CreateModel(
            name='UrlGrupoFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL completa del grupo de Facebook', max_length=500, verbose_name='URL del Grupo')),
                ('activo', models.BooleanField(default=True, help_text='Si esta URL está activa para publicar', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('grupo', models.ForeignKey(help_text='Grupo al que pertenece esta URL', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='publicadorFacebook.grupofacebook', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'URL de Grupo Facebook',
                'verbose_name_plural': 'URLs de Grupos Facebook',
                'ordering': ['grupo__nombre', '-activo', 'url'],
                'indexes': [models.Index(fields=['grupo', 'activo'], name='publicadorF_grupo_i_1d7ddd_idx'), models.Index(fields=['url'], name='publicadorF_url_d36afb_idx')],
                'unique_together': {('grupo', 'url')},
            },
        ),
        migrations.AddIndex(
            model_name='publicaciongrupofacebook',
            index=models.Index(fields=['anuncio', 'grupo_facebook'], name='publicadorF_anuncio_391d01_idx'),
        ),
        migrations.AddIndex(
            model_name='publicaciongrupofacebook',
            index=models.Index(fields=['fecha_publicacion'], name='publicadorF_fecha_p_7b5dde_idx'),
        ),
        migrations.AddIndex(
            model_name='publicaciongrupofacebook',
            index=models.Index(fields=['exitosa'], name='publicadorF_exitosa_167092_idx'),
        ),
        migrations.AddIndex(
            model_name='publicaciongrupofacebook',
            index=models.Index(fields=['anuncio', 'exitosa'], name='publicadorF_anuncio_d44b34_idx'),
        ),
        migrations.AddIndex(
            model_name='publicaciongrupofacebook',
            index=models.Index(fields=['anuncio', 'fecha_publicacion'], name='idx_anuncio_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='publicaciongrupofacebook',
            unique_together={('anuncio', 'grupo_facebook', 'fecha_publicacion')},
        ),
        migrations.AddIndex(
            model_name='grupofacebook',
            index=models.Index(fields=['nombre'], name='publicadorF_nombre_1084f2_idx'),
        ),
        migrations.AddIndex(
            model_name='grupofacebook',
            index=models.Index(fields=['activo'], name='publicadorF_activo_96b399_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['activo'], name='publicadorF_activo_47ec6e_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['fecha_inicio'], name='publicadorF_fecha_i_f21e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['publicaciones_programadas'], name='publicadorF_publica_689a48_idx'),
        ),
    ]
